raymed/apps/helpdesk/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as standart_views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

app_name = "helpdesk"

urlpatterns = [

    # path('', views.main_index, name = 'main_index'),
    # path('post_error_<int:device_id>', views.post_error, name ='post_error'),
    path('views_errors_for_this_user<int:user_id>', views.views_errors_for_this_user, name ='views_errors_for_this_user'),
    path('view_all_errors', views.view_all_errors, name ='view_all_errors'),
    path('edit_error_<int:error_id>', views.edit_error, name ='edit_error'),
    path('index_for_buh_<int:user_id>', views.index_for_buh, name ='index_for_buh'),
    path('detail_error_<int:error_id>', views.detail_error, name ='detail_error'),
    # path('post_other_error', views.post_other_error, name ='post_other_error'),
    # path('edit_other_error_<int:error_id>', views.edit_other_error, name ='edit_other_error'),
    path('post_global_error', views.post_global_error, name ='post_global_error'),

]

raymed/apps/raymedasset/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as standart_views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

app_name = "raymedasset"

urlpatterns = [

    path('search_for_name', views.search_for_name, name = 'search_for_name'),
    path('<int:person_id>/', views.detail_person, name = 'detail_person'),
    path('search_for_type_device', views.search_for_type_device, name = 'search_for_type_device'),
    path('add_person_page', views.add_person_page , name = "add_person_page"),
    path('add_device_page', views.add_device_page, name = 'add_device_page'),
    path('search_for_number_account',views.search_for_number_account, name = 'search_for_number_account'),
    path('see_all_device', views.see_all_device, name = 'see_all_device'),
    path('<int:person_id>/add_device_page/', views.add_device_page_this_person, name = 'add_device_page_this_person'),
    path('transfer_device_<int:device_id>', views.transfer_device, name = 'transfer_device'),
    path('transfer_subdevice_<int:subdevice_id>', views.transfer_subdevice, name = 'transfer_subdevice'),
    path('transfer_device_<int:device_id>/delete_device', views.delete_device, name = 'delete_device'),
    path('transfer_subdevice_<int:subdevice_id>/delete_subdevice', views.delete_subdevice, name = 'delete_subdevice'),
    path('see_all_person', views.see_all_person, name = 'see_all_person'),
    path('edit_person_<int:person_id>', views.edit_person, name = 'edit_person'),
    path('search', views.search, name = 'search'),
    path('admin/', admin.site.urls),
    path('see_device_for_number_account_<str:number_account>', views.see_device_for_number_account, name = 'see_device_for_number_account'),
    path('see_device_without_person', views.see_device_without_person, name = 'see_device_without_person'),
    path('search_for_department', views.search_for_department, name = 'search_for_department'),
    path('see_all_this_department_<str:name_department>', views.see_all_this_department, name = 'see_all_this_department'),
    path('see_all_this_type_device_<str:type_device>', views.see_all_this_type_device, name = 'see_all_this_type_device'),
    path('add_subdevice_<int:device_id>', views.add_subdevice, name = 'add_subdevice'),
    path('see_all_subdevice', views.see_all_subdevice, name = 'see_all_subdevice'),
    path('history_move_this_device_<int:device_id>', views.history_move_this_device, name = 'history_move_this_device'),
    path('test', views.test, name = 'test'),



]

raymed/apps/registration/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as standart_views

app_name = "registration"

urlpatterns = [
    path('index', views.index, name = 'index'),
    path('', views.home, name = 'home'),
    # path('home', views.home, name = 'home'),
    path('login', standart_views.LoginView.as_view(), name='login'),
    path('logout/', standart_views.LogoutView.as_view(), name='logout'),
    # path('register/', views.register, name = 'register'),
    #


]

raymed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from raymedasset import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('raymedasset.urls')),
    path('',include('registration.urls')),
    path('',include('helpdesk.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

raymed/apps/helpdesk/models.py
from django.db import models
from django.contrib.auth.models import User
from raymedasset.models import Device, Person, Subdevice

class Error(models.Model):
    STATUS_CHOICE = (
("wait","Ожидание"),
("in_work", "В работе"),
("ready", "Готово"))

    person = models.ForeignKey(User, blank = True, on_delete = models.CASCADE)
    device = models.ForeignKey(Device, blank = True, null = True, on_delete = models.CASCADE)
    message_error = models.TextField('Неисправность', null = True, blank = True)
    status = models.CharField("Статус обращения",max_length = 30, default = STATUS_CHOICE[0][0], choices = STATUS_CHOICE )
    time_post_message = models.DateTimeField('Время обращения')
    solutions = models.TextField('Решение проблемы', null = True, blank = True)
    image_error = models.ImageField('Скриншот ошибки', upload_to = 'images/error/',  blank=True)

    def __str__(self):
        if self.device:
            return  str(self.device)
        else:
            return str(self.person)

    class Meta:
        verbose_name = 'Проблема'
        verbose_name_plural = 'Проблемы'

raymed/apps/raymedasset/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms
from django.core.validators import FileExtensionValidator
from django.conf import settings
from django.contrib.auth.models import User
# from phonenumber_field.modelfields import PhoneNumberField

#проверка на длину серии паспорта
def validators_serial(value):
    if not value.isdigit():
        raise forms.ValidationError(_("Серия паспорта должна состоять только из цифр"))
    elif len(str(value)) != 4 :
        raise forms.ValidationError(_('Серия пасорта должна состоять из 4 цифр'))

#проверка на длину серии паспорта
def validators_number(value):
    if not value.isdigit():
        raise forms.ValidationError(_("Номер паспорта должен состоять только из цифр"))
    elif len(str(value)) != 6 :
        raise forms.ValidationError(_('Номер пасорта должен состоять из 6 цифр'))

#проверка внутреннего телефона на правильность ввода(должны быть только цифры)
def validators_number_phone(value):
    if not value.isdigit():
        raise forms.ValidationError(_("Номер телефона должен состоять только из цифр"))

def validators_FIO(value):
    if not value.isalpha():
        raise forms.ValidationError(_("Это поле должно содержать только алфавитные символы"))

class Person(models.Model):
    DEPARTMENT_CHOICE = (
        ('manage', "Управление"),
        ('sekretary', "Секретариат"),
        ('buhgaltery' , "Бухгалтерия"),
        ('ekonom' , " Эконом.отдел"),
        ('legal' , "Правовой"),
        ('registration' , "Регистрации и сертификации"),
        ('commercial', "Коммерческий"),
        ("hr", "Управление персоналом"),
        ("tender" , "Тендерный"),
        ("warehouse", "Склад"),
        ("transport", "Транспортный"),
        ("logistics", "Логистика"),
        ("purchases", "Закупки"),
        ("security" , "Безопасность"),
        ("ahch",  "АХЧ"),
        ("it", "IT"),
        ("production", "Производство")
        )

    user = models.OneToOneField(User, blank = True, default = '0', on_delete = models.CASCADE)
    first_name = models.CharField('Имя',  max_length = 15, validators = [validators_FIO])
    last_name = models.CharField('Фамилия',  max_length = 15, validators = [validators_FIO])
    middle_name = models.CharField('Отчество', blank = True,  max_length = 15, validators = [validators_FIO])
    department = models.CharField('Отдел',  blank = True,   max_length = 20, choices = DEPARTMENT_CHOICE)
    # amount_laptop = models.IntegerField(default=0)
    # amount_desktop = models.IntegerField(default=0)
    # amount_monitor = models.IntegerField(default=0)
    # amount_monoblock = models.IntegerField(default=0)
    # amount_ex_disk = models.IntegerField(default=0)
    # amount_flash = models.IntegerField(default=0)
    date_add_person = models.DateTimeField('Дата добавление сотрудника в БД')
    image = models.ImageField('Фото', upload_to = 'images/avatar/',  blank=True)
    # internal_number_phone = models.CharField('Внутренний номер телефона', max_length = 3, blank = True,  validators = [validators_number_phone])
    # number_phone = models.CharField('Номер телефона', max_length = 11, blank = True, validators = [validators_number_phone] )
    date_birthday = models.DateField('Дата рождения',  blank = False)
    email = models.EmailField('Почта', max_length = 50, blank = True)
    email_password = models.CharField('Пароль для входа в почту', max_length = 50, blank = True) #скрытое поле. Нужно для отправки сообщений на почту почты



    # Сохранение ФИО в нижнем регистре
    def save(self, *args, **kwargs):
        self.first_name = self.first_name.lower()
        self.last_name = self.last_name.lower()
        self.middle_name = self.middle_name.lower()
        return super(Person, self).save(*args, **kwargs)

    def __str__(self):
        s = self.last_name  + ' ' +self.first_name
        return s

    def soon_birthday(self):
        now = datetime.now()
        birthday = datetime(now.year, self.date_birthday.month, self.date_birthday.day)
        birthday2 = datetime(now.year+1, self.date_birthday.month, self.date_birthday.day)
        days = (min(birthday, birthday2) - now).days
        if days < 0:
            days += 365
        if days <= 30:
            return True
        else:
            return False

    def display_fname(self):
        return self.first_name[:1].upper() + self.first_name[1:]

    def display_lname(self):
        return self.last_name[:1].upper() + self.last_name[1:]

    def display_mname(self):
        return self.middle_name[:1].upper() + self.middle_name[1:]



    def display_number_phone(self):
        num = self.number_phone
        num = str('(%s)-%s-%s-%s' % (num[:1], num[1:4], num[4:6], num[6:8]))
        return num

    class Meta:
        verbose_name='Сотрудник'
        verbose_name_plural='Сотрудники'



class Device(models.Model):
    DEVICE_CHOICE = (
("desktop","Стационарный компьютер"),
("laptop", "Ноутбук"),
("monoblock", "Моноблок"),
("monitor", "Монитор"),
("externaldisk", "Внешний жесткий диск"),
("flashdrive", "Флешка"),
("periphery", "Мышь\клавиатура"),
("case", "Сумка"),
('other','Другое'),
)

    TYPE_ORGANIZATION = (
("raymed_tg_pvt","Раймед ТГ ПВТ"),
("raymed_t", "Раймед-Т"),
("miocardium", "Миокардиум"),
)
    person = models.ForeignKey(Person, null = True, blank = True, on_delete = models.SET_NULL)
    device_type =  models.CharField('Тип устройства',max_length = 15, choices = DEVICE_CHOICE )
    model = models.CharField('Модель устройства',max_length = 50)
    descriptions = models.TextField('Описание', null = True, blank = True)
    serial_number = models.CharField('Серийный номер', max_length = 25)
    number_account = models.CharField('Номер счета',max_length = 50,  blank = True) # номер счета
    provider =  models.CharField('Поставщик', max_length = 15, null = True, blank = True)
    cost = models.IntegerField('Стоимость(руб)', null = True, blank = True, default = 0)
    closed_document = models.FileField('Закрывающий документ', upload_to = 'documents/', blank = True, validators = [FileExtensionValidator(['pdf', 'jpg', 'docx'])])
    organization = models.CharField("Организация", max_length = 20, blank = True, null = True, choices = TYPE_ORGANIZATION)

    def display_person(self):
        person = self.person
        person = str(person).split(' ')
        return person[0][:1].upper()+person[0][1:]+' '+person[1][:1].upper() + person[1][1:]

    def __str__(self):
        return  str(self.person)+' '+ self.device_type +' ' +  self.model +' '+ self.serial_number

    def display_number_account(self):
        number_account = self.number_account
        return number_account.upper()

    class Meta:
        verbose_name='Устройство'
        verbose_name_plural='Устройства'

class Subdevice(models.Model):
    TYPE_HARDWARE = (
("ssd","SSD"),
("ram", "Оперативная память"),
)

    TYPE_ORGANIZATION = (
("raymed_tg_pvt","Раймед ТГ ПВТ"),
("raymed_t", "Раймед-Т"),
("miocardium", "Миокардиум"),
)
    device = models.ForeignKey(Device, on_delete = models.CASCADE)
    type = models.CharField('Тип устройства', max_length = 20, choices = TYPE_HARDWARE)
    model = models.CharField('Модель устройства',max_length = 50)
    descriptions = models.TextField('Описание', null = True, blank = True)
    serial_number = models.CharField('Серийный номер', max_length = 25)
    number_account = models.CharField('Номер счета',max_length = 50,  blank = True) # номер счета
    provider =  models.CharField('Поставщик', max_length = 15, null = True, blank = True)
    cost = models.IntegerField('Стоимость(руб)', null = True, blank = True, default = 0)
    closed_document = models.FileField('Закрывающий документ', upload_to = 'documents/', blank = True, validators = [FileExtensionValidator(['pdf', 'jpg', 'docx'])])
    organization = models.CharField("Организация", max_length = 20, blank = True, null = True, choices = TYPE_ORGANIZATION, default = TYPE_ORGANIZATION[0])

    def display_person(self):
        person = self.device.person
        person = str(person).split(' ')
        return person[0][:1].upper()+person[0][1:]+' '+person[1][:1].upper() + person[1][1:]

    def display_number_account(self):
        number_account = self.number_account
        return number_account.upper()

    def __str__(self):
        return self.type +' '+  self.model

    class Meta:
        verbose_name='Комплектующие'
        verbose_name_plural='Комплектующие'

class HistoryMoveDevice(models.Model):
    device = models.ForeignKey(Device, null = True, blank = True, on_delete = models.CASCADE)
    old_person = models.ForeignKey(Person, null = True, blank = True, default = None, on_delete = models.CASCADE)
    current_person = models.ForeignKey(Person, null = True, blank = True,  on_delete = models.CASCADE, related_name = 'current')
    date_get_device = models.DateField('Дата получения устройства', default = datetime.now())
    date_receive_device = models.DateField('Дата конца владения устройством', blank = True, null = True)

    def __str__(self):
        return str(self.device) +" "+ str(self.date_get_device)+" "+ str(self.date_receive_device)

    class Meta:
        verbose_name='История перемещения'
        verbose_name_plural='Истории перемещения'

raymed/apps/helpdesk/forms.py
from django import forms
from .models import Person, Device, Subdevice, Error
from django.forms import ModelForm, Textarea
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


# Форма сообщения об ошибке
class ErrorForm(ModelForm):
    class Meta:
        model = Error
        fields = ["message_error", 'image_error']
        widgets = {
            'message_error': Textarea(attrs={'rows': 5, 'cols': "150%"}),
        }

    def __init__(self, *args, **kwargs):
        super(ErrorForm, self).__init__(*args, **kwargs)
        self.fields['message_error'].help_text = 'Обязательное поле'
        self.fields['image_error'].help_text = 'НЕ обязательное поле'

# форма редактирования неисправности
class EditErrorForm(ModelForm):
    class Meta:
        model = Error
        fields = ["message_error", 'status', 'solutions']
        widgets = {
            'message_error': Textarea(attrs={'rows': 5, 'cols': "150%"}),
            'solutions': Textarea(attrs={'rows': 5, 'cols': "150%"}),
        }

    def __init__(self, *args, **kwargs):
        super(EditErrorForm, self).__init__(*args, **kwargs)
        self.fields['message_error'].help_text = 'Обязательное поле'

# оишбка без техники, которая есть в БД
class OtherErrorForm(ModelForm):
    class Meta:
        model = Error
        fields = ["message_error", 'image_error']
        widgets = {
            'message_error': Textarea(attrs={'rows': 5, 'cols': "150%"}),
            'solutions': Textarea(attrs={'rows': 5, 'cols': "150%"}),
        }

    def __init__(self, *args, **kwargs):
        super(OtherErrorForm, self).__init__(*args, **kwargs)
        self.fields['message_error'].help_text = 'Обязательное поле'
        self.fields['image_error'].help_text = 'НЕ обязательное поле'


# форма редактирования неисправности без устройства
class EditOtherErrorForm(ModelForm):
    class Meta:
        model = Error
        fields = ["message_error", 'status', 'solutions']
        widgets = {
            'message_error': Textarea(attrs={'rows': 5, 'cols': "150%"}),
            'solutions': Textarea(attrs={'rows': 5, 'cols': "150%"}),
        }

    def __init__(self, *args, **kwargs):
        super(EditOtherErrorForm, self).__init__(*args, **kwargs)
        self.fields['message_error'].help_text = 'Обязательное поле'

raymed/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>
    {% block title %}
    Django Authentication Example
    {% endblock%}
  </title>
</head>
<style>
  input[type=text],
  input[type=number],
  select {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: c7c7c7;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    font: color:red;
    transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
  }

  input[type=file] {
    display: block;
    width: 100%
  }

  body {
    /* Градиент */
    background: linear-gradient(#c6dcf5, #0777f7) fixed;
  }

  a {
    color: black;
  }

  a:hover {
    color: red;
  }
</style>

<body>
  {% block upper%}
  <div style="min-width:100%">
        <nav class="navbar navbar-expand-lg sticky-top" style="background-color: #6c71cc;">
          <a class="navbar-brand" href="{% url 'registration:index'%}" style="color:black">Главная</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              {% if not is_buh %}
              {% if is_admin or is_hr %}
              <li>
                <div class="dropdown">
                  <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:black">
                    Сотрудники
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <a class="dropdown-item" href="{% url 'raymedasset:add_person_page' %}">Добавить сотрудника</a>
                    <a class="dropdown-item" href="{% url 'raymedasset:see_all_person' %}">Показать всех сотрудников</a>
                  </div>
                </div>
              </li>
              {% endif %}
              {% endif %}
              {% if is_admin %}
              <li>
                <div class="dropdown">
                  <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:black">
                    Устройства
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <a class="dropdown-item" href="{% url 'raymedasset:add_device_page' %}">Добавить устройство</a>
                    <a class="dropdown-item" href="{% url 'raymedasset:see_all_device' %}">Показать все устройства</a>
                    <a class="dropdown-item" href="{% url 'raymedasset:see_device_without_person' %}">Показать устройства без владельца</a>
                    <a class="dropdown-item" href="{% url 'raymedasset:see_all_subdevice' %}">Показать все комплеутющие</a>
                    <a class="dropdown-item" href="{% url 'raymedasset:test' %}">Test</a>
                  </div>
                </div>
              </li>
              {% endif %}
              {% if is_buh %}
              <li>
                <div class="dropdown">
                  <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:black">
                    Список устройств/сотрудников
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <a class="dropdown-item" href="{% url 'raymedasset:see_all_person' %}">Показать всех сотрудников</a>
                    <a class="dropdown-item" href="{% url 'raymedasset:see_all_device' %}">Показать все устройства</a>
                    <a class="dropdown-item" href="{% url 'raymedasset:see_device_without_person' %}">Показать устройства без владельца</a>
                  </div>
                </div>
              </li>
              {% endif %}
            </ul>
            {% if is_admin %}
            <!-- <a class="btn btn-warning my-2 my-sm-0" href="{% url 'helpdesk:view_all_errors' %}">HelpDesk</a>
            <a class="btn btn-success my-2 my-sm-0" href="{% url 'admin:index' %}">Админка</a> -->
            <a class="navbar-brand btn btn-warning my-2 my-sm-0" href="{% url 'helpdesk:view_all_errors'%}" style="color:black">HelpDesk</a>
            <a class="navbar-brand btn btn-success my-2 my-sm-0" href="{% url 'admin:index'%}" style="color:black">Админка</a>
            {% endif %}
            <a class="navbar-brand btn btn-danger my-2 my-sm-0" href="{% url 'registration:logout'%}" style="color:black">Выход</a>
            <!-- <a class="btn btn-danger my-2 my-sm-0" href="{% url 'registration:logout' %}">Выйти</a> -->
        </nav>
      </div>
  </div>

    {% endblock %}
    {% block main  %}

    {% endblock %}

    {%block content%}
    {% endblock %}

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
</body>


</html>

raymed/templates/test.html
{% extends 'base.html' %}

{% block title %} Все что есть {% endblock%}

{% block main %}


 {% endblock %}

{% block content %}


{% if all_person %}
      {% for i in all_person %}
            <h3>{{ i }}
            {{ i.device_set.count }} </h3>


             {% if i.device_set.count > 0 %}
                {% for j in i.device_set.all %}
                  <p>  <b> Модель: </b> {{ j.model }};  <b>Тип устройства:</b> {{j.device_type }};  <b>Серийный номер:</b> {{ j.serial_number }};  </p>
                {% endfor %}
            {% else %}
                <p>У Сотрудника нет едениц техники </p>
            {% endif %}


      {% endfor %}



{% else %}
    <p> Пока нет пользователей </p>
{% endif %}

{% if device_without_person %}
    <h3>Техника без владельца\На складе </h3>
    {% for i in device_without_person %}
      <p>  <b> Модель: </b> {{ i.model }} ; <b>Тип устройства:</b> {{i.device_type }};  <b>Серийный номер:</b> {{ i.serial_number }} ;</p>
    {% endfor %}
{% endif %}

--------------
{% for i in all_person %}
  <!-- {{i}} <br> -->
    {% for j in i.device_set.all %}
        {% if j.model == search_type_device %}

            {{ j.model }} <br>
        {% endif %}
    {% endfor %}
{% endfor %}



{% endblock %}
<!-- Тестовый коммент №1 -->
<!-- Тестовый коммент №2 -->