raymed/apps/helpdesk/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as standart_views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

app_name = "helpdesk"

urlpatterns = [

    # path('', views.main_index, name = 'main_index'),
    # path('post_error_<int:device_id>', views.post_error, name ='post_error'),
    path('views_errors_for_this_user<int:user_id>', views.views_errors_for_this_user, name ='views_errors_for_this_user'),
    path('view_all_errors', views.view_all_errors, name ='view_all_errors'),
    path('edit_error_<int:error_id>', views.edit_error, name ='edit_error'),
    path('index_for_buh_<int:user_id>', views.index_for_buh, name ='index_for_buh'),
    path('detail_error_<int:error_id>', views.detail_error, name ='detail_error'),
    # path('post_other_error', views.post_other_error, name ='post_other_error'),
    # path('edit_other_error_<int:error_id>', views.edit_other_error, name ='edit_other_error'),
    path('post_global_error', views.post_global_error, name ='post_global_error'),

]

raymed/apps/raymedasset/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as standart_views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

app_name = "raymedasset"

urlpatterns = [

    path('search_for_name', views.search_for_name, name = 'search_for_name'),
    path('<int:person_id>/', views.detail_person, name = 'detail_person'),
    path('search_for_type_device', views.search_for_type_device, name = 'search_for_type_device'),
    path('add_person_page', views.add_person_page , name = "add_person_page"),
    path('add_device_page', views.add_device_page, name = 'add_device_page'),
    path('search_for_number_account',views.search_for_number_account, name = 'search_for_number_account'),
    path('see_all_device', views.see_all_device, name = 'see_all_device'),
    path('<int:person_id>/add_device_page/', views.add_device_page_this_person, name = 'add_device_page_this_person'),
    path('transfer_device_<int:device_id>', views.transfer_device, name = 'transfer_device'),
    path('transfer_subdevice_<int:subdevice_id>', views.transfer_subdevice, name = 'transfer_subdevice'),
    path('transfer_device_<int:device_id>/delete_device', views.delete_device, name = 'delete_device'),
    path('transfer_subdevice_<int:subdevice_id>/delete_subdevice', views.delete_subdevice, name = 'delete_subdevice'),
    path('see_all_person', views.see_all_person, name = 'see_all_person'),
    path('edit_person_<int:person_id>', views.edit_person, name = 'edit_person'),
    path('search', views.search, name = 'search'),
    path('admin/', admin.site.urls),
    path('see_device_for_number_account_<str:number_account>', views.see_device_for_number_account, name = 'see_device_for_number_account'),
    path('see_device_without_person', views.see_device_without_person, name = 'see_device_without_person'),
    path('search_for_department', views.search_for_department, name = 'search_for_department'),
    path('see_all_this_department_<str:name_department>', views.see_all_this_department, name = 'see_all_this_department'),
    path('see_all_this_type_device_<str:type_device>', views.see_all_this_type_device, name = 'see_all_this_type_device'),
    path('add_subdevice_<int:device_id>', views.add_subdevice, name = 'add_subdevice'),
    path('see_all_subdevice', views.see_all_subdevice, name = 'see_all_subdevice'),
    path('history_move_this_device_<int:device_id>', views.history_move_this_device, name = 'history_move_this_device'),
    path('test', views.test, name = 'test'),



]

raymed/apps/registration/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as standart_views

app_name = "registration"

urlpatterns = [
    path('index', views.index, name = 'index'),
    path('', views.home, name = 'home'),
    # path('home', views.home, name = 'home'),
    path('login', standart_views.LoginView.as_view(), name='login'),
    path('logout/', standart_views.LogoutView.as_view(), name='logout'),
    # path('register/', views.register, name = 'register'),
    #


]

raymed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from raymedasset import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('raymedasset.urls')),
    path('',include('registration.urls')),
    path('',include('helpdesk.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

raymed/apps/helpdesk/models.py
from django.db import models
from django.contrib.auth.models import User
from raymedasset.models import Device, Person, Subdevice

class Error(models.Model):
    STATUS_CHOICE = (
("wait","Ожидание"),
("in_work", "В работе"),
("ready", "Готово"))

    person = models.ForeignKey(User, blank = True, on_delete = models.CASCADE)
    device = models.ForeignKey(Device, blank = True, null = True, on_delete = models.CASCADE)
    message_error = models.TextField('Неисправность', null = True, blank = True)
    status = models.CharField("Статус обращения",max_length = 30, default = STATUS_CHOICE[0][0], choices = STATUS_CHOICE )
    time_post_message = models.DateTimeField('Время обращения')
    solutions = models.TextField('Решение проблемы', null = True, blank = True)
    image_error = models.ImageField('Скриншот ошибки', upload_to = 'images/error/',  blank=True)

    def __str__(self):
        if self.device:
            return  str(self.device)
        else:
            return str(self.person)

    class Meta:
        verbose_name = 'Проблема'
        verbose_name_plural = 'Проблемы'

raymed/apps/raymedasset/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms
from django.core.validators import FileExtensionValidator
from django.conf import settings
from django.contrib.auth.models import User
# from phonenumber_field.modelfields import PhoneNumberField

#проверка на длину серии паспорта
def validators_serial(value):
    if not value.isdigit():
        raise forms.ValidationError(_("Серия паспорта должна состоять только из цифр"))
    elif len(str(value)) != 4 :
        raise forms.ValidationError(_('Серия пасорта должна состоять из 4 цифр'))

#проверка на длину серии паспорта
def validators_number(value):
    if not value.isdigit():
        raise forms.ValidationError(_("Номер паспорта должен состоять только из цифр"))
    elif len(str(value)) != 6 :
        raise forms.ValidationError(_('Номер пасорта должен состоять из 6 цифр'))

#проверка внутреннего телефона на правильность ввода(должны быть только цифры)
def validators_number_phone(value):
    if not value.isdigit():
        raise forms.ValidationError(_("Номер телефона должен состоять только из цифр"))

def validators_FIO(value):
    if not value.isalpha():
        raise forms.ValidationError(_("Это поле должно содержать только алфавитные символы"))

class Person(models.Model):
    DEPARTMENT_CHOICE = (
        ('manage', "Управление"),
        ('sekretary', "Секретариат"),
        ('buhgaltery' , "Бухгалтерия"),
        ('ekonom' , " Эконом.отдел"),
        ('legal' , "Правовой"),
        ('registration' , "Регистрации и сертификации"),
        ('commercial', "Коммерческий"),
        ("hr", "Управление персоналом"),
        ("tender" , "Тендерный"),
        ("warehouse", "Склад"),
        ("transport", "Транспортный"),
        ("logistics", "Логистика"),
        ("purchases", "Закупки"),
        ("security" , "Безопасность"),
        ("ahch",  "АХЧ"),
        ("it", "IT"),
        ("production", "Производство")
        )

    user = models.OneToOneField(User, blank = True, default = '0', on_delete = models.CASCADE)
    first_name = models.CharField('Имя',  max_length = 15, validators = [validators_FIO])
    last_name = models.CharField('Фамилия',  max_length = 15, validators = [validators_FIO])
    middle_name = models.CharField('Отчество', blank = True,  max_length = 15, validators = [validators_FIO])
    department = models.CharField('Отдел',  blank = True,   max_length = 20, choices = DEPARTMENT_CHOICE)
    # amount_laptop = models.IntegerField(default=0)
    # amount_desktop = models.IntegerField(default=0)
    # amount_monitor = models.IntegerField(default=0)
    # amount_monoblock = models.IntegerField(default=0)
    # amount_ex_disk = models.IntegerField(default=0)
    # amount_flash = models.IntegerField(default=0)
    date_add_person = models.DateTimeField('Дата добавление сотрудника в БД')
    image = models.ImageField('Фото', upload_to = 'images/avatar/',  blank=True)
    # internal_number_phone = models.CharField('Внутренний номер телефона', max_length = 3, blank = True,  validators = [validators_number_phone])
    # number_phone = models.CharField('Номер телефона', max_length = 11, blank = True, validators = [validators_number_phone] )
    date_birthday = models.DateField('Дата рождения',  blank = False)
    email = models.EmailField('Почта', max_length = 50, blank = True)
    email_password = models.CharField('Пароль для входа в почту', max_length = 50, blank = True) #скрытое поле. Нужно для отправки сообщений на почту почты



    # Сохранение ФИО в нижнем регистре
    def save(self, *args, **kwargs):
        self.first_name = self.first_name.lower()
        self.last_name = self.last_name.lower()
        self.middle_name = self.middle_name.lower()
        return super(Person, self).save(*args, **kwargs)

    def __str__(self):
        s = self.last_name  + ' ' +self.first_name
        return s

    def soon_birthday(self):
        now = datetime.now()
        birthday = datetime(now.year, self.date_birthday.month, self.date_birthday.day)
        birthday2 = datetime(now.year+1, self.date_birthday.month, self.date_birthday.day)
        days = (min(birthday, birthday2) - now).days
        if days < 0:
            days += 365
        if days <= 30:
            return True
        else:
            return False

    def display_fname(self):
        return self.first_name[:1].upper() + self.first_name[1:]

    def display_lname(self):
        return self.last_name[:1].upper() + self.last_name[1:]

    def display_mname(self):
        return self.middle_name[:1].upper() + self.middle_name[1:]



    def display_number_phone(self):
        num = self.number_phone
        num = str('(%s)-%s-%s-%s' % (num[:1], num[1:4], num[4:6], num[6:8]))
        return num

    class Meta:
        verbose_name='Сотрудник'
        verbose_name_plural='Сотрудники'



class Device(models.Model):
    DEVICE_CHOICE = (
("desktop","Стационарный компьютер"),
("laptop", "Ноутбук"),
("monoblock", "Моноблок"),
("monitor", "Монитор"),
("externaldisk", "Внешний жесткий диск"),
("flashdrive", "Флешка"),
("periphery", "Мышь\клавиатура"),
("case", "Сумка"),
('other','Другое'),
)

    TYPE_ORGANIZATION = (
("raymed_tg_pvt","Раймед ТГ ПВТ"),
("raymed_t", "Раймед-Т"),
("miocardium", "Миокардиум"),
)
    person = models.ForeignKey(Person, null = True, blank = True, on_delete = models.SET_NULL)
    device_type =  models.CharField('Тип устройства',max_length = 15, choices = DEVICE_CHOICE )
    model = models.CharField('Модель устройства',max_length = 50)
    descriptions = models.TextField('Описание', null = True, blank = True)
    serial_number = models.CharField('Серийный номер', max_length = 25)
    number_account = models.CharField('Номер счета',max_length = 50,  blank = True) # номер счета
    provider =  models.CharField('Поставщик', max_length = 15, null = True, blank = True)
    cost = models.IntegerField('Стоимость(руб)', null = True, blank = True, default = 0)
    closed_document = models.FileField('Закрывающий документ', upload_to = 'documents/', blank = True, validators = [FileExtensionValidator(['pdf', 'jpg', 'docx'])])
    organization = models.CharField("Организация", max_length = 20, blank = True, null = True, choices = TYPE_ORGANIZATION)

    def display_person(self):
        person = self.person
        person = str(person).split(' ')
        return person[0][:1].upper()+person[0][1:]+' '+person[1][:1].upper() + person[1][1:]

    def __str__(self):
        return  str(self.person)+' '+ self.device_type +' ' +  self.model +' '+ self.serial_number

    def display_number_account(self):
        number_account = self.number_account
        return number_account.upper()

    class Meta:
        verbose_name='Устройство'
        verbose_name_plural='Устройства'

class Subdevice(models.Model):
    TYPE_HARDWARE = (
("ssd","SSD"),
("ram", "Оперативная память"),
)

    TYPE_ORGANIZATION = (
("raymed_tg_pvt","Раймед ТГ ПВТ"),
("raymed_t", "Раймед-Т"),
("miocardium", "Миокардиум"),
)
    device = models.ForeignKey(Device, on_delete = models.CASCADE)
    type = models.CharField('Тип устройства', max_length = 20, choices = TYPE_HARDWARE)
    model = models.CharField('Модель устройства',max_length = 50)
    descriptions = models.TextField('Описание', null = True, blank = True)
    serial_number = models.CharField('Серийный номер', max_length = 25)
    number_account = models.CharField('Номер счета',max_length = 50,  blank = True) # номер счета
    provider =  models.CharField('Поставщик', max_length = 15, null = True, blank = True)
    cost = models.IntegerField('Стоимость(руб)', null = True, blank = True, default = 0)
    closed_document = models.FileField('Закрывающий документ', upload_to = 'documents/', blank = True, validators = [FileExtensionValidator(['pdf', 'jpg', 'docx'])])
    organization = models.CharField("Организация", max_length = 20, blank = True, null = True, choices = TYPE_ORGANIZATION, default = TYPE_ORGANIZATION[0])

    def display_person(self):
        person = self.device.person
        person = str(person).split(' ')
        return person[0][:1].upper()+person[0][1:]+' '+person[1][:1].upper() + person[1][1:]

    def display_number_account(self):
        number_account = self.number_account
        return number_account.upper()

    def __str__(self):
        return self.type +' '+  self.model

    class Meta:
        verbose_name='Комплектующие'
        verbose_name_plural='Комплектующие'

class HistoryMoveDevice(models.Model):
    device = models.ForeignKey(Device, null = True, blank = True, on_delete = models.CASCADE)
    old_person = models.ForeignKey(Person, null = True, blank = True, default = None, on_delete = models.CASCADE)
    current_person = models.ForeignKey(Person, null = True, blank = True,  on_delete = models.CASCADE, related_name = 'current')
    date_get_device = models.DateField('Дата получения устройства', default = datetime.now())
    date_receive_device = models.DateField('Дата конца владения устройством', blank = True, null = True)

    def __str__(self):
        return str(self.device) +" "+ str(self.date_get_device)+" "+ str(self.date_receive_device)

    class Meta:
        verbose_name='История перемещения'
        verbose_name_plural='Истории перемещения'

raymed/apps/helpdesk/forms.py
from django import forms
from .models import Person, Device, Subdevice, Error
from django.forms import ModelForm, Textarea
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


# Форма сообщения об ошибке
class ErrorForm(ModelForm):
    class Meta:
        model = Error
        fields = ["message_error", 'image_error']
        widgets = {
            'message_error': Textarea(attrs={'rows': 5, 'cols': "150%"}),
        }

    def __init__(self, *args, **kwargs):
        super(ErrorForm, self).__init__(*args, **kwargs)
        self.fields['message_error'].help_text = 'Обязательное поле'
        self.fields['image_error'].help_text = 'НЕ обязательное поле'

# форма редактирования неисправности
class EditErrorForm(ModelForm):
    class Meta:
        model = Error
        fields = ["message_error", 'status', 'solutions']
        widgets = {
            'message_error': Textarea(attrs={'rows': 5, 'cols': "150%"}),
            'solutions': Textarea(attrs={'rows': 5, 'cols': "150%"}),
        }

    def __init__(self, *args, **kwargs):
        super(EditErrorForm, self).__init__(*args, **kwargs)
        self.fields['message_error'].help_text = 'Обязательное поле'

# оишбка без техники, которая есть в БД
class OtherErrorForm(ModelForm):
    class Meta:
        model = Error
        fields = ["message_error", 'image_error']
        widgets = {
            'message_error': Textarea(attrs={'rows': 5, 'cols': "150%"}),
            'solutions': Textarea(attrs={'rows': 5, 'cols': "150%"}),
        }

    def __init__(self, *args, **kwargs):
        super(OtherErrorForm, self).__init__(*args, **kwargs)
        self.fields['message_error'].help_text = 'Обязательное поле'
        self.fields['image_error'].help_text = 'НЕ обязательное поле'


# форма редактирования неисправности без устройства
class EditOtherErrorForm(ModelForm):
    class Meta:
        model = Error
        fields = ["message_error", 'status', 'solutions']
        widgets = {
            'message_error': Textarea(attrs={'rows': 5, 'cols': "150%"}),
            'solutions': Textarea(attrs={'rows': 5, 'cols': "150%"}),
        }

    def __init__(self, *args, **kwargs):
        super(EditOtherErrorForm, self).__init__(*args, **kwargs)
        self.fields['message_error'].help_text = 'Обязательное поле'

raymed/templates/raymedasset/detail_person.html
{% extends 'base.html' %}

{% block title %} Информация о сотруднике {% endblock%}

{% block main %}

<!-- Если пользователь не из кадров то -->
{% if not is_hr %}
<div class="container-fluid">

  <div class="row justify-content-center">
    <!-- <div class="col-2" style='margin-top:2%'> -->
      <!-- <img src="https://raymedtgpvt.sharepoint.com/sites/raymed2/Shared%20Documents/BD!.jpg" height="150px" width="150px" alt='Я'> -->
    <div class="col col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl col-xxl-7" style="border-radius: 10px; margin-top:2%; margin-right:2%">
      <img src="{{name_person.image.url}}" height="150px" width="150px" alt='Я'>
      <br>
      <b>Фамилия : </b> {{name_person.display_lname}} <br>
      <b>Имя: </b>{{name_person.display_fname}}<br>
      <b> Отчество:</b> {{name_person.display_mname}}<br>
      {% if name_person.department %}
        <b>Отдел : </b> <a href="{% url 'raymedasset:see_all_this_department' name_person.department %}">{{name_person.get_department_display}}</a> <br>
      {% else %}
        <b>Отдел : </b> - <br>
      {% endif %}
      <b>Количество устройств: </b> {{name_person.device_set.count}}<br>
      {% if is_hr %}
      <b>Серия паспорта</b>: {{name_person.serial_pasport}} <br>
      <b>Номер паспорта</b>: {{name_person.number_pasport}} <br>
      {% endif %}
      <br>
      {% if is_admin %}
      <hr>
      <a href="{% url 'raymedasset:add_device_page_this_person' name_person.id %}"><b>Добавить устройство сотруднику</b></a>
      <!-- <a href="{{name_person.image}}" download>Скачать</a> -->
      {% endif %}
      {% if not is_buh %}
      <hr>
      <a href="{% url 'raymedasset:edit_person' name_person.id %}"><b>Редактировать данные сотрудника</b></a>
      {% endif %}
    </div>

    <div class="col col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-10 col-xxl-7" style="border-radius: 10px;margin-right:2%">

      {% if name_person.device_set.count == 0 %}
      <h4 style="margin-top:5%" align='center'>У сотрудника нет единиц техники</h4>
      {% else %}
      <table class="table table-hover" style="margin-top:3%" >
        <thead class="thead-light">
          <tr align='center'>
            <th></th>
            <th style ="vertical-align:middle" width="8%"><b>Тип устройства</b></th>
            <th><b>Модель устройства</b></th>
            <th width="10%"><b>Серийный номер</b></th>
            <th width="21%"><b>Описание</b></th>
            <th><b>Организация</b></th>
            <th width="10%"><b>Номер счета</b></th>
            <th>Документ</th>
            <th></th>
          </tr>
        </thead>

        {% for i in name_person.device_set.all %}
          <tr align='center'>
            {% if i.device_type == "monoblock" or  i.device_type == "laptop" or  i.device_type == "desktop"  %}
              <td><a href="{% url 'raymedasset:add_subdevice' i.id %}"><img src="/media/images/plus.png" alt="img" width="20px" height="20px"></a> {{i.type_device}}</td>
            {% else %}
              <td></td>
            {% endif %}
            <td><a href="{% url 'raymedasset:see_all_this_type_device' i.device_type %}">{{i.get_device_type_display}}</a></td>
            <td><a href="{% url 'raymedasset:history_move_this_device' i.id %}"> {{i.model }} </a></td>
            <td> {{i.serial_number}}</td>
            <td>{{i.descriptions}}</td>
            <td>{{i.get_organization_display}}</td>
            {% if i.number_account %}
                <td><a href="{% url 'raymedasset:see_device_for_number_account' i.number_account %}">{{i.display_number_account}}</a></td>
            {% else %}
                <td>-</td>
            {% endif %}
            {% if i.closed_document %}
                <td><a href="{{i.closed_document.url}}" target="_blank">Документ</a></td>
            {% else %}
                <td>Отсутствует</td>
            {% endif %}

            {% if not is_hr %}
                <td><a href="{% url 'raymedasset:transfer_device' i.id %}"><img src="/media/images/pencil.png" alt="img" width="20px" height="20px"></a> </td>
            {% endif %}
          </tr>
          {% if i.subdevice_set.all %}
            {% for j in i.subdevice_set.all %}
            <tr align='center'>
              <td> </td>
              <td></td>
              <td><b>{{j.get_type_display}}</b> {{j.model }}</td>
              <td> {{j.serial_number}}</td>
              <td>{{j.descriptions}}</td>
              <td>{{i.get_organization_display}}</td>
              {% if j.number_account %}
                  <td><a href="{% url 'raymedasset:see_device_for_number_account' j.number_account %}">{{j.display_number_account}}</a></td>
              {% else %}
                  <td>-</td>
              {% endif %}
              {% if j.closed_document %}
                  <td><a href="{{j.closed_document.url}}" target="_blank">Документ</a></td>
              {% else %}
                  <td>Отсутствует</td>
              {% endif %}

              {% if not is_hr %}
                  <td><a href="{% url 'raymedasset:transfer_subdevice' j.id %}"><img src="/media/images/pencil.png" alt="img" width="20px" height="20px"></a> </td>
              {% endif %}
            </tr>
            {% endfor %}
          {% endif %}
          {% endfor %}


      </table>


      <!--  -->


      <hr>
      <table class="table" style='margin-top:5%'>
        <thead class="thead-light">
          <tr align="center">
            <th>Кол-во стационарных ПК</th>
            <th>Кол-во ноутбуков</th>
            <th>Кол-во мониторов</th>
            <th>Кол-во моноблоков</th>
            <th>Кол-во внешних HDD</th>
            <th>Кол-во флешек</th>
          </tr>
        </thead>
        <tr align="center">
          <td>{{amount_desktop}}</td>
          <td>{{amount_laptop}}</td>
          <td>{{amount_monitor}}</td>
          <td>{{amount_monoblock}}</td>
          <td>{{amount_ex_disk}}</td>
          <td>{{amount_flash}}</td>
        </tr>
      </table>
      {% endif %}

    </div>
    <div class="col-2">
    </div>

  </div>

</div>


<!-- Если пользователь ИЗ КАДРОВ!!! -->
{% else %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col col-xs-6 col-sm-6 col-md-5 col-lg-4 col-xl-2 col-xxl-2" style='margin-top:3%;' >
            <img src="{{name_person.image.url}}" height="250px" width="250px" alt='Я'> <br><br>
              <a href="{% url 'raymedasset:edit_person' name_person.id %}" style='margin-top:3%' ><b>Редактировать данные сотрудника</b></a>
        </div>

        <div class="col col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-7 col-xxl-7" style='margin-top:1.5%;'>
          <table class="table table-bordered" style="margin-top:3%" >
            <thead class="thead-light">
              <tr align='center'>
                <th width="25%"><b>Фамилия</b></th>
                <td > {{name_person.last_name}}</td>
              </tr>
                <tr align='center'>
                <th width="25%"><b>Имя</b></th>
                <td>{{name_person.first_name}}</td>
              </tr>
              <tr align='center'>
                <th width="25%"><b>Отчество</b></th>
                <td>{{name_person.middle_name}}</td>
              </tr>
              <tr align='center'>
                <th width="25%"><b>Дата рождения</b></th>
                <td>{{name_person.date_birthday}}</td>
              </tr>
              <tr align='center'>
                <th width="25%"><b>Отдел</b></th>
                <td>{{name_person.get_department_display}}</td>
              </tr>
              <tr align='center'>
                <th width="25%"><b>Серия паспорта</b></th>
                <td>{{name_person.serial_pasport}}</td>
              </tr>
              <tr align='center'>
                <th width="25%"><b>Номер паспорта</b></th>
                <td>{{name_person.number_pasport}}</td>
              </tr>
              <tr align='center'>
                <th width="25%"><b>Внутренний номер телефона</b></th>
                <td>{{name_person.internal_number_phone}}</td>
              </tr>
              <tr align='center'>
                <th width="25%"><b>Номер телефона</b></th>
                {% if name_person.number_phone %}
                <td>{{name_person.display_number_phone}}</td>
                {% else %}
                <td>-</td>
                {% endif %}
              </tr>
            </thead>
            </table>
        </div>

        <div class="col col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-3 col-xxl-7" >

        </div>

  </div>
  </div>

{% endif %}
{% endblock %}

raymed/templates/raymedasset/see_all_person.html
{% extends 'base.html' %}

{% block title %} Информация о сотруднике {% endblock%}

{% block main %}

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-8 col-xxl-7" style="border-radius: 10px">


      <!-- ---------------------------------------------- -->
      <table class="table table-bordered" style = "margin-top:2%">
        <thead class="thead-light">
          <tr align='center'>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Отдел</th>
          {% if is_admin %}
          <th>кол-во техники</th>
          {% endif %}
          </tr>
        </thead>

        {% for person in all_person %}
        <tr align='center'>
          <td><a href="{% url 'raymedasset:detail_person' person.id %}">{{person.display_lname}}</a></td>
          <td><a href="{% url 'raymedasset:detail_person' person.id %}"> {{person.display_fname}}</a> </td>
          <td><a href="{% url 'raymedasset:detail_person' person.id %}">  {{person.display_mname}} </a></td>
          {% if person.department %}
            <td><a href="{% url 'raymedasset:see_all_this_department' person.department %}">{{person.get_department_display}}</a></td>
          {% else %}
            <td>-</td>
          {% endif %}
          
          {% if is_admin %}
          <td>{{person.device_set.count}}</td>
        {% endif %}
        </tr>
        {% endfor %}
        <hr>
        <tr align = 'center'>
          <td colspan="4"> <b>Всего {{count_person}} сотрудников</b>  </td>
        </tr>
      </table>

    </div>
  </div>
</div>

{% endblock %}